### ISSUE TITLE
Suggestion to delete only generated files in /docs

### ISSUE THREAD

**Issue by grossbart** [gcanti/docs-ts#1]
I've been trying to put together a PR for fp-ts documentation. I would like to take advantage of the Just-the-Docs theme and its sidebar, but what's missing is a place to write documentation because, at the moment, `docs-ts` deletes all files in `/docs` (with small exceptions), which makes this difficult. I would suggest to only delete `*.ts.md` files in docs.

I understand that you have already written several pieces of documentation in fp-ts’s root folder as markdown files. However, due to technical restrictions from GitHub Pages, it would be much easier to work with documentation if everything were in the `/docs` folder (also the logo, for example, which currently can't really be referenced from docs).

I would like to achieve something like this, where the sidebar provides some high-level entry points (there would be more, but not many more):

<img width="990" alt="bildschirmfoto 2019-03-03 um 09 46 00" src="https://user-images.githubusercontent.com/10811/53692975-316c9100-3d99-11e9-84f3-9d1bc9b0b1dc.png">

<img width="1100" alt="bildschirmfoto 2019-03-03 um 09 49 31" src="https://user-images.githubusercontent.com/10811/53692999-a9d35200-3d99-11e9-911d-0af49dc39fe5.png">

What would further simplify this is if the generated module files would be placed in `/docs/modules/*.ts.md`; or even `/docs/modules-gen` or something with a disclamer that these are generated files. (They could use Jekyll’s `permalink` frontmatter to state that they are really found at `/modules`.)

How do you see this? The way you have set out to document your libraries with `docs-ts` seems to be focused on generated API documentation. This is already a great win, definitely! But I would like to argue that your libraries could greatly benefit from more comprehensive documentation for different levels of knowledge, similar to what you're doing with your recent dev.to articles. (I'm thinking of my co-workers who often struggle to find their way around.) If you would be open to changing this, I think that the `README.md` files would change as well, providing more information on how to develop the library and contribute and moving user-facing documentation into `/docs`.

**Comment by gcanti** [comment]
@grossbart good idea!

I have made the required changes in the master branch of `docs-ts`.

This is the result of a test repo https://gcanti.github.io/test-just-the-docs/

**Comment by gcanti** [comment]
@grossbart just applied these changes to the `fp-ts` repo. We can move the other `.md` files, logo, svg etc... to the `/docs` folder now

**Comment by grossbart** [comment]
Thanks! I'll update my branches and send some small initial PRs to fp-ts, hopefully by this evening.
