### ISSUE TITLE
Peer dependency upon TypeScript should support 4.x

### ISSUE THREAD

**Issue by samhh** [gcanti/docs-ts#19]

**Comment by gcanti** [comment]
@samhh I should change `peerDependencies` to

```
"typescript": "^3.3.1 || ^4.x"
```

right?

**Comment by samhh** [comment]
That looks good to me based upon [Yarn's docs](https://classic.yarnpkg.com/en/docs/dependency-versions/#toc-unions).

I think the [`||` may be optional](https://github.com/kulshekhar/ts-jest/blob/master/package.json#L72).
