### ISSUE TITLE
`Error: Cannot find module 'prettier'`

### ISSUE THREAD

**Issue by thought2** [gcanti/docs-ts#22]
After installing `docs-ts` via `yarn add docs-ts` I run `yarn docs-ts` and get this error:

`Error: Cannot find module 'prettier'`

I have to manually `yarn add prettier` to make it work. 

Is `prettier` maybe a dependency and not a dev dependency of `docs-ts`?

**Comment by gillchristian** [comment]
I would say it should be made a peer dependency instead.
