### ISSUE TITLE
Output path generation is incorrect on Windows 10

### ISSUE THREAD

**Issue by rzeigler** [gcanti/docs-ts#4]
**Do you want to request a _feature_ or report a _bug_?**
A bug

**What is the current behavior?**
docs-ts produces output paths such as `docs\modules\.md` for every module on Windows 10

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**
run docs-ts on windows

**What is the expected behavior?**
output path should mirror the module source filename.

**Which versions of docs-ts, and which browser and OS are affected by this issue? Did this work in previous versions of docs-ts?**
🤷‍♂

**Comment by gcanti** [comment]
https://github.com/gcanti/docs-ts/pull/5
