### ISSUE TITLE
Can't ignore private methods from being generated

### ISSUE THREAD

**Issue by eduhenke** [gcanti/docs-ts#42]
**Do you want to request a _feature_ or report a _bug_?**
_bug_

**What is the current behavior?**
I annotate my private method with a JSDoc containing @internal or @ignore, and the documentation is generated

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**

```typescript
/**
 * Description
 *
 * @example
 * const a = 3
 * 
 * @category Animal
 */
export default class Dog {
  public bark() {}
  /** @internal */
  private scratch() {}
}
```
**What is the expected behavior?**
I expect the documentation to not be generated

**Which versions of docs-ts, and which browser and OS are affected by this issue? Did this work in previous versions of docs-ts?**
v0.6.9, first time I use it.

**Comment by IMax153** [comment]
Looks like we're not filtering out `method`s that we `shouldIgnore` in the `Parser`.

https://github.com/gcanti/docs-ts/blob/00d85a4031d574aa1b4c2abc9903a867468e4cbe/src/Parser.ts#L598-L612

I can take a look into fixing this next week
